google_analytics_id: UA-33449675-8

repository: https://github.com/BYR-STYLE/BYR-STYLE

timezone: Asia/Shanghai

title: BYR-STYLE
description: Make Life BYR-STYLE
url: https://byr-style.irockbunny.com
contact: contact[at]irockbunny[dot]com

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net

github: https://github.com/BYR-STYLE

image: /img/Avatar.png
logo: /img/Avatar.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor