version:
  jquery: 3.1.1
  jquery_migrate: 3.0.0
  bootstrap: 3.3.7
  font_awesome: 4.7.0

google_analytics_id: UA-33449675-8

repository: https://github.com/BYR-STYLE/BYR-STYLE

timezone: Asia/Shanghai

name: BYR-STYLE
author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net
description: Make Life BYR-STYLE
url: http://byr-style.irockbunny.com
contact: contact[at]irockbunny[dot]com
github: https://github.com/BYR-STYLE

logo: /img/Avatar.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor